// <auto-generated />
using System;
using MFL.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MFL.Data.Migrations
{
    [DbContext(typeof(MFLContext))]
    [Migration("20201006065326_AlterDropIdsType")]
    partial class AlterDropIdsType
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MFL.Data.Entities.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Birthdate")
                        .HasColumnType("datetime");

                    b.Property<int>("CbsId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<int>("DraftPick")
                        .HasColumnType("int");

                    b.Property<int>("DraftRound")
                        .HasColumnType("int");

                    b.Property<string>("DraftTeam")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("DraftYear")
                        .HasColumnType("int");

                    b.Property<int>("EspnId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("FleaflickerId")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .HasColumnType("varchar(110)")
                        .HasMaxLength(110);

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<int>("Jersey")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("NflId")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Position")
                        .HasColumnType("varchar(10)")
                        .HasMaxLength(10);

                    b.Property<int>("RotowireId")
                        .HasColumnType("int");

                    b.Property<int>("RotoworldId")
                        .HasColumnType("int");

                    b.Property<byte[]>("SportsdataId")
                        .IsRequired()
                        .HasColumnType("varbinary(16)");

                    b.Property<int>("StatsGlobalId")
                        .HasColumnType("int");

                    b.Property<int>("StatsId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Team")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.Property<int?>("TeamId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("MFL.Data.Entities.WaiverTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("DropIds")
                        .HasColumnType("text");

                    b.Property<int>("LeagueId")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("WaiverTransactions");
                });

            modelBuilder.Entity("MFL.Data.Entities.WaiverTransaction", b =>
                {
                    b.HasOne("MFL.Data.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
